export const bo_cau_hoi = [
    { id: 1, q: "Trong Squid Game, trò chơi đầu tiên là Đèn Xanh Đèn Đỏ đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 2, q: "Firebase Realtime Database đồng bộ dữ liệu theo thời gian thực đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 3, q: "HTML5 Canvas dùng để vẽ đồ họa bằng ngôn ngữ nào?", a: ["JavaScript", "Python"], c: 0 },
    { id: 4, q: "Hệ điều hành Linux phân biệt chữ hoa và chữ thường đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 5, q: "Giao thức kết nối an toàn bảo mật cho Web hiện nay là gì?", a: ["HTTP", "HTTPS"], c: 1 },
    { id: 6, q: "RAM là bộ nhớ trong sẽ bị mất dữ liệu khi mất điện đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 7, q: "Bộ xử lý trung tâm của máy tính được gọi tắt là gì?", a: ["CPU", "GPU"], c: 0 },
    { id: 8, q: "Cú pháp import/export mô-đun của ES6 chạy trực tiếp được trên file:// không?", a: ["Được", "Không"], c: 1 },
    { id: 9, q: "Trong ngôn ngữ JavaScript, mảng bắt đầu từ chỉ số (index) mấy?", a: ["0", "1"], c: 0 },
    { id: 10, q: "Búp bê quản trò trong Squid Game tên là Younghee đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 11, q: "Firebase RTDB lưu trữ dữ liệu dưới cấu trúc dạng nào?", a: ["Bảng SQL", "Cây JSON"], c: 1 },
    { id: 12, q: "Lệnh console.log() trong JS dùng để làm gì?", a: ["In dữ liệu debug", "Tạo cửa sổ mới"], c: 0 },
    { id: 13, q: "Git là hệ thống quản lý mã nguồn phân tán đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 14, q: "Hàm Math.random() trong JS có bao giờ trả về đúng bằng 1.0 không?", a: ["Có", "Không"], c: 1 },
    { id: 15, q: "Độ phân giải Full HD tiêu chuẩn là bao nhiêu?", a: ["1280x720", "1920x1080"], c: 1 },
    { id: 16, q: "Kiểu dữ liệu Boolean trong lập trình có mấy giá trị?", a: ["2", "4"], c: 0 },
    { id: 17, q: "Vercel hỗ trợ deploy tự động qua kho lưu trữ GitHub đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 18, q: "Lệnh nào dùng để khai báo một hằng số không đổi trong JS?", a: ["let", "const"], c: 1 },
    { id: 19, q: "CSS viết tắt của từ Cascading Style Sheets đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 20, q: "Trong ngôn ngữ C, hàm printf() dùng để làm gì?", a: ["Nhập dữ liệu", "Xuất dữ liệu"], c: 1 },
    { id: 21, q: "Chip ESP32 tích hợp sẵn kết nối Wi-Fi và Bluetooth đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 22, q: "Mạng máy tính LAN là mạng diện rộng hay mạng cục bộ?", a: ["Cục bộ", "Diện rộng"], c: 0 },
    { id: 23, q: "Trong lập trình, s sập nguồn hoặc tràn bộ nhớ đệm gọi là gì?", a: ["Crash", "Compile"], c: 0 },
    { id: 24, q: "Đơn vị đo tần số quét của màn hình máy tính là gì?", a: ["Hz", "FPS"], c: 0 },
    { id: 25, q: "Sự kiện mousedown kích hoạt khi nào?", a: ["Thả chuột ra", "Nhấn giữ chuột xuống"], c: 1 },
    { id: 26, q: "Đồ họa Pixel Art dựa trên các khối vuông nhỏ gọi là gì?", a: ["Vector", "Pixel"], c: 1 },
    { id: 27, q: "Phương thức window.location.reload() dùng để làm gì?", a: ["Chuyển trang", "Tải lại trang"], c: 1 },
    { id: 28, q: "Lệnh git clone dùng để tải một kho mã nguồn trên mạng về máy đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 29, q: "Trong CSS, thuộc tính color dùng để đổi màu cho cái gì?", a: ["Màu nền", "Màu chữ"], c: 1 },
    { id: 30, q: "Ổ cứng SSD có tốc độ đọc ghi nhanh hơn ổ cứng HDD đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 31, q: "Hàm setTimeout trong JS dùng để trì hoãn thực thi một hành động đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 32, q: "Trong Squid Game, người chơi mang áo khoác màu gì?", a: ["Xanh lá cây", "Hồng cánh sen"], c: 0 },
    { id: 33, q: "Lập trình nhúng (Embedded) là viết code cho phần cứng thông minh đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 34, q: "Hàm Math.floor(4.9) trong JavaScript trả về kết quả là mấy?", a: ["4", "5"], c: 0 },
    { id: 35, q: "Ký hiệu '===' trong JS dùng để so sánh cả giá trị và kiểu dữ liệu đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 36, q: "Thẻ <canvas> có thể tự xử lý render đồ họa mà không cần JavaScript không?", a: ["Có", "Không"], c: 1 },
    { id: 37, q: "Cổng mạng HTTP mặc định chạy trên cổng (port) số mấy?", a: ["80", "443"], c: 0 },
    { id: 38, q: "Địa chỉ IP mặc định của Localhost thường là gì?", a: ["127.0.0.1", "192.168.1.1"], c: 0 },
    { id: 39, q: "Lệnh JSON.stringify() dùng để biến Object thành chuỗi String đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 40, q: "Trong Squid Game, lính gác mang mặt nạ có hình gì?", a: ["Tròn, Vuông, Tam giác", "Ngôi sao, Trăng, Hoa"], c: 0 },
    { id: 41, q: "Ngôn ngữ nào chạy trực tiếp được trên trình duyệt web của client?", a: ["C++", "JavaScript"], c: 1 },
    { id: 42, q: "Bộ nhớ Cache giúp tăng tốc độ truy xuất dữ liệu của CPU đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 43, q: "Thuộc tính `display: none` trong CSS sẽ ẩn hoàn toàn phần tử đó đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 44, q: "API viết tắt của Application Programming Interface đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 45, q: "Trong lập trình, lỗi cú pháp khiến code không thể biên dịch gọi là gì?", a: ["Runtime Error", "Syntax Error"], c: 1 },
    { id: 46, q: "Trong JS, 'NaN' viết tắt của từ 'Not a Number' đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 47, q: "Nút bấm HTML được tạo bằng thẻ nào công khai?", a: ["<input>", "<button>"], c: 1 },
    { id: 48, q: "Firebase RTDB hỗ trợ lưu trữ các file ảnh, video dung lượng lớn không?", a: ["Có", "Không"], c: 1 },
    { id: 49, q: "Hàm requestAnimationFrame tối ưu hơn lệnh setInterval để làm vòng lặp game đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 50, q: "Người chơi số 456 trong Squid Game tên là Seong Gi-hun đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 51, q: "Hệ nhị phân chỉ sử dụng hai ký số là 0 và 1 đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 52, q: "Hàm prompt() trong trình duyệt dùng để làm gì?", a: ["Hiện thông báo", "Nhập chuỗi text"], c: 1 },
    { id: 53, q: "Đuôi tệp tin của font chữ Pixel cổ điển thường là gì?", a: [".ttf", ".mp3"], c: 0 },
    { id: 54, q: "Lệnh nào dùng để tạo vòng lặp vô hạn cơ bản trong lập trình?", a: ["while(true)", "if/else"], c: 0 },
    { id: 55, q: "Khi dùng Git, lệnh nào dùng để đẩy code từ máy lên GitHub?", a: ["git pull", "git push"], c: 1 },
    { id: 56, q: "Để chọn phần tử theo ID trong JS, ta dùng lệnh document.getElementById() đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 57, q: "Trong CSS, thuộc tính `cursor: pointer` biến con trỏ chuột thành hình bàn tay đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 58, q: "Mô hình mạng mà một máy quản lý dữ liệu cho các máy khác gọi là gì?", a: ["Peer-to-Peer", "Client-Server"], c: 1 },
    { id: 59, q: "Tệp tin cấu hình giao diện trang web có đuôi mở rộng là gì?", a: [".css", ".html"], c: 0 },
    { id: 60, q: "Nhân vật chính thắng cuộc Squid Game mùa đầu tiên nhận được tiền thưởng đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 61, q: "Cú pháp vòng lặp `for` dùng để lặp với số lần biết trước đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 62, q: "Phương thức array.push() dùng để thêm một phần tử vào cuối mảng đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 63, q: "Hệ quản trị cơ sở dữ liệu MongoDB thuộc loại NoSQL đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 64, q: "Trong JS, kiểu dữ liệu của số 10 và chuỗi '10' có giống nhau không?", a: ["Có", "Không"], c: 1 },
    { id: 65, q: "Giao thức mạng HTTPS chạy mặc định trên cổng (port) nào?", a: ["80", "443"], c: 1 },
    { id: 66, q: "Biến khai báo bằng từ khóa `let` có phạm vi hoạt động trong khối block đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 67, q: "Hàm `.getContext('2d')` được gọi từ đối tượng nào trong DOM?", a: ["<div>", "<canvas>"], c: 1 },
    { id: 68, q: "Để xóa một phòng trên Firebase, ta dùng lệnh dbRemove() đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 69, q: "Trong CSS, hiệu ứng animation dùng để tạo chuyển động động cho UI đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 70, q: "Ông già số 001 trong Squid Game chính là trùm cuối đứng sau trò chơi đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 71, q: "Một byte dữ liệu bằng bao nhiêu bit?", a: ["8 bit", "16 bit"], c: 0 },
    { id: 72, q: "Lệnh `break` dùng để thoát khỏi vòng lặp ngay lập tức đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 73, q: "Hàm `setInterval` lặp lại hành động sau một khoảng thời gian cố định đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 74, q: "Trình duyệt tự động chặn âm thanh tự phát (autoplay) nếu người dùng chưa tương tác đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 75, q: "Trong mảng JS, lệnh `.filter()` dùng để lọc các phần tử thỏa mãn điều kiện đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 76, q: "Từ khóa `this` trong JS đại diện cho đối tượng hiện tại đang thực thi đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 77, q: "Để đo khoảng cách giữa 2 điểm trong không gian 2D, ta dùng định lý Pytago đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 78, q: "Lệnh `git status` dùng để kiểm tra trạng thái các file thay đổi đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 79, q: "Trong thiết kế giao diện, 'Responsive' nghĩa là tự co giãn theo kích thước màn hình đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 80, q: "Trò chơi tách kẹo đường trong Squid Game yêu cầu người chơi cắt hình không vỡ đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 81, q: "Mã màu Hex sinh ra màu trắng tuyệt đối là gì?", a: ["#000000", "#ffffff"], c: 1 },
    { id: 82, q: "Mã màu Hex sinh ra màu đen tuyệt đối là gì?", a: ["#000000", "#ffffff"], c: 0 },
    { id: 83, q: "Hàm `Math.ceil(4.1)` trong JavaScript trả về kết quả là mấy?", a: ["4", "5"], c: 1 },
    { id: 84, q: "Lệnh `localStorage.getItem()` dùng để đọc dữ liệu lưu trữ tạm thời của trình duyệt đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 85, q: "Trong ngôn ngữ C, toán tử `%` dùng để chia lấy phần dư đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 86, q: "Phương thức `ctx.clearRect()` dùng để xóa một vùng trên màn hình Canvas đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 87, q: "Firebase RTDB tính phí gói miễn phí dựa trên dung lượng lưu trữ và băng thông đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 88, q: "Trong JS, một chuỗi rỗng `''` khi ép kiểu sang Boolean sẽ mang giá trị gì?", a: ["true", "false"], c: 1 },
    { id: 89, q: "Hành động đẩy một phần tử mới lên Firebase dùng phương thức `dbSet` hoặc `dbUpdate` đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 90, q: "Người chơi mang áo số 067 trong Squid Game là cô gái người Triều Tiên Kang Sae-byeok đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 91, q: "Tệp tin thực thi chính của dự án web mặc định đặt tên là gì?", a: ["script.js", "index.html"], c: 1 },
    { id: 92, q: "Lệnh `git init` dùng để khởi tạo một kho Git mới tại thư mục hiện tại đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 93, q: "Trong CSS, thuộc tính `z-index` quyết định thứ tự xếp chồng lớp hiển thị đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 94, q: "Ngôn ngữ Markdown dùng để viết tài liệu định dạng văn bản nhanh đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 95, q: "Khi dùng lệnh `dbUpdate` trên Firebase, các node dữ liệu không được nhắc tới sẽ bị xóa sạch đúng không?", a: ["Có", "Không"], c: 1 },
    { id: 96, q: "Lệnh `console.error()` dùng để in ra dòng thông báo lỗi màu đỏ trong tab Console đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 97, q: "Để lấy tọa độ click chuột tương đối trong Canvas, ta phải trừ đi tọa độ bounding box của Canvas đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 98, q: "Trình duyệt Chrome sử dụng bộ Engine V8 để biên dịch ngôn ngữ JavaScript đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 99, q: "Tên tệp tin icon nhỏ hiển thị trên tab trình duyệt web được gọi phổ biến là gì?", a: ["Favicon", "Logo"], c: 0 },
    { id: 100, q: "Mùa 2 của loạt phim sinh tồn Squid Game đã chính thức được công chiếu đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 101, q: "Mặt Trời thực chất là một ngôi sao đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 102, q: "Hành tinh nào nằm ở vị trí gần Mặt Trời nhất trong Hệ Mặt Trời?", a: ["Sao Thủy", "Sao Kim"], c: 0 },
    { id: 103, q: "Sao Hỏa còn được gọi phổ biến với cái tên là Hành tinh Đỏ đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 104, q: "Trái Đất mất bao lâu để thực hiện xong một vòng quay quanh Mặt Trời?", a: ["365 ngày", "24 giờ"], c: 0 },
    { id: 105, q: "Mặt Trăng có khả năng tự phát ra ánh sáng không?", a: ["Có", "Không"], c: 1 },
    { id: 106, q: "Hành tinh nào có kích thước lớn nhất trong Hệ Mặt Trời?", a: ["Sao Mộc", "Sao Thổ"], c: 0 },
    { id: 107, q: "Dải Ngân Hà (Milky Way) của chúng ta có cấu trúc hình dạng gì?", a: ["Hình xoắn ốc", "Hình tròn"], c: 0 },
    { id: 108, q: "Vận tốc di chuyển của ánh sáng nhanh hơn vận tốc của âm thanh đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 109, q: "Năm ánh sáng là đơn vị dùng để đo khoảng cách hay thời gian?", a: ["Khoảng cách", "Thời gian"], c: 0 },
    { id: 110, q: "Lực hấp dẫn của Mặt Trăng là nguyên nhân chính gây ra hiện tượng thủy triều?", a: ["Đúng", "Sai"], c: 0 },
    { id: 111, q: "Sao Kim là hành tinh có nhiệt độ bề mặt nóng nhất trong Hệ Mặt Trời đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 112, q: "Lực hấp dẫn của hố đen mạnh đến mức ánh sáng cũng không thể thoát ra đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 113, q: "Hành tinh nào nổi tiếng với vành đai băng và đá lớn xung quanh?", a: ["Sao Thổ", "Sao Hải Vương"], c: 0 },
    { id: 114, q: "Mặt Trời được cấu tạo chủ yếu từ hai nguyên tố khí nào?", a: ["Hydro và Heli", "Oxy và Nitơ"], c: 0 },
    { id: 115, q: "Trạm vũ trụ quốc tế ISS luôn có phi hành gia sinh sống liên tục đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 116, q: "Hiện tượng nguyệt thực xảy ra khi Trái Đất nằm giữa Mặt Trời và Mặt Trăng đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 117, q: "Sao Chổi được cấu tạo chủ yếu từ thành phần băng dính bụi và đá đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 118, q: "Sao Diêm Vương (Pluto) hiện nay vẫn được tính là hành tinh vòng chính đúng không?", a: ["Đúng", "Sai"], c: 1 },
    { id: 119, q: "Mảnh thiên thạch từ vũ trụ rơi sống sót xuống bề mặt Trái Đất gọi là gì?", a: ["Vẫn thạch", "Sao băng"], c: 0 },
    { id: 120, q: "Kính viễn vọng không gian nổi tiếng Hubble do tổ chức nào phóng lên?", a: ["NASA", "ESA"], c: 0 },
    { id: 121, q: "Cá voi xanh là loài động vật có kích thước lớn nhất hành tinh hiện nay đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 122, q: "Loài chim nào giữ kỷ lục có tốc độ chạy nhanh nhất thế giới trên cạn?", a: ["Đà điểu", "Chim ưng"], c: 0 },
    { id: 123, q: "Cá mập là loài động vật có hệ khung xương cấu tạo hoàn toàn bằng sụn đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 124, q: "Chim cánh cụt trong tự nhiên sinh sống chủ yếu ở Nam Cực hay Bắc Cực?", a: ["Nam Cực", "Bắc Cực"], c: 0 },
    { id: 125, q: "Báo săn (Cheetah) là loài động vật có tốc độ chạy nhanh nhất trên cạn đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 126, q: "Loài thú nào là loài duy nhất có khả năng bay lượn thực sự?", a: ["Dơi", "Sóc bay"], c: 0 },
    { id: 127, q: "Khủng long đã tuyệt chủng cách đây khoảng bao nhiêu triệu năm?", a: ["65 triệu năm", "6 triệu năm"], c: 0 },
    { id: 128, q: "Ốc sên có khả năng ngủ đông liên tục suốt vài năm đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 129, q: "Cấu tạo cơ thể của loài sứa biển có chứa não bộ và tim không?", a: ["Có", "Không"], c: 1 },
    { id: 130, q: "Loài động vật nào dưới đại dương sở hữu cấu tạo có tới 3 quả tim?", a: ["Bạch tuộc", "Cá heo"], c: 0 },
    { id: 131, q: "Lạc đà dùng bướu trên lưng để tích trữ nước trực tiếp đúng không?", a: ["Đúng", "Sai"], c: 1 },
    { id: 132, q: "Một số loài rùa có khả năng hỗ trợ thở bằng hậu môn khi ở dưới nước đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 133, q: "Muỗi đực là đối tượng trực tiếp hút máu người để nuôi trứng đúng không?", a: ["Đúng", "Sai"], c: 1 },
    { id: 134, q: "Máu của loài tôm hùm có màu gì đặc trưng do chứa nguyên tố đồng?", a: ["Màu xanh dương", "Màu đỏ"], c: 0 },
    { id: 135, q: "Chuột túi Kangaroo chỉ sinh sống trong môi trường tự nhiên ở châu lục nào?", a: ["Châu Úc", "Châu Phi"], c: 0 },
    { id: 136, q: "Ong mật sẽ bị chết ngay sau khi thực hiện động tác đốt người đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 137, q: "Thú mỏ vịt là loài động vật thuộc lớp thú nhưng lại đẻ trứng đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 138, q: "Loài cá nào có tập tính bơi ngược dòng thác nước về nguồn để đẻ trứng?", a: ["Cá hồi", "Cá thu"], c: 0 },
    { id: 139, q: "Lớp da dưới lông của con gấu bắc cực thực chất có màu gì?", a: ["Màu đen", "Màu hồng"], c: 0 },
    { id: 140, q: "Voi là loài động vật có vú duy nhất trên cạn không thể nhảy đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 141, q: "Ở áp suất tiêu chuẩn, nước tinh khiết sẽ sôi ở nhiệt độ bao nhiêu?", a: ["100 độ C", "0 độ C"], c: 0 },
    { id: 142, q: "Công thức hóa học tiêu chuẩn của nước tinh khiết là gì?", a: ["H2O", "CO2"], c: 0 },
    { id: 143, q: "Khí Oxy chiếm tỷ lệ phần trăm thể tích lớn nhất trong khí quyển Trái Đất đúng không?", a: ["Đúng", "Sai"], c: 1 },
    { id: 144, q: "Lõi trong cùng của Trái Đất cấu tạo chủ yếu từ hai kim loại nào?", a: ["Sắt và Niken", "Vàng và Bạc"], c: 0 },
    { id: 145, q: "Kim cương và than chì đều được cấu tạo từ chung nguyên tố carbon đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 146, q: "Hiện tượng cầu vồng xảy ra do ánh sáng Mặt Trời bị tán sắc qua giọt nước đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 147, q: "Thủy ngân là kim loại duy nhất ở thể lỏng trong điều kiện nhiệt độ phòng đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 148, q: "Dòng điện xoay chiều được viết tắt ký hiệu hệ thống là gì?", a: ["AC", "DC"], c: 0 },
    { id: 149, q: "Ai là nhà khoa học phát hiện ra lực vạn vật hấp dẫn nhờ quả táo rơi?", a: ["Isaac Newton", "Albert Einstein"], c: 0 },
    { id: 150, q: "Ánh sáng trắng thực chất là tập hợp của dải gồm nhiều màu sắc đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 151, q: "Chỉ số độ pH bằng 7 đại diện cho môi trường dung dịch gì?", a: ["Trung tính", "Axit"], c: 0 },
    { id: 152, q: "Khí thải nào gây ra hiện tượng hiệu ứng nhà kính lớn nhất do con người?", a: ["CO2", "O2"], c: 0 },
    { id: 153, q: "Băng nổi được trên nước do mật độ khối lượng của băng nhẹ hơn nước lỏng đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 154, q: "Sấm sét xảy ra do hiện tượng phóng điện giữa các đám mây đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 155, q: "Âm thanh hoàn toàn không thể truyền đi được trong môi trường chân không đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 156, q: "Độ cận thị của mắt người được đo bằng đơn vị tiêu chuẩn nào?", a: ["Diop", "Decibel"], c: 0 },
    { id: 157, q: "Thuyết tương đối nổi tiếng thế giới do nhà vật lý nào phát minh ra?", a: ["Albert Einstein", "Nikola Tesla"], c: 0 },
    { id: 158, q: "Sóng thần thường được kích hoạt từ các trận động đất dưới đáy biển đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 159, q: "Khí Heli nhẹ hơn không khí nên bóng bay bơm Heli sẽ tự bay lên đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 160, q: "Tia cực tím (UV) từ ánh sáng Mặt Trời có khả năng gây hại cho da đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 161, q: "Hệ Mặt Trời của chúng ta nằm trong thiên hà có tên là Andromeda đúng không?", a: ["Đúng", "Sai"], c: 1 },
    { id: 162, q: "Khoảng cách trung bình từ Trái Đất đến Mặt Trời khoảng bao nhiêu triệu km?", a: ["150 triệu km", "15 triệu km"], c: 0 },
    { id: 163, q: "Hành tinh nào được đặt tên theo thần chiến tranh Mars của thần thoại La Mã?", a: ["Sao Hỏa", "Sao Kim"], c: 0 },
    { id: 164, q: "Kính viễn vọng James Webb thu thập hình ảnh vũ trụ chủ yếu bằng tia nào?", a: ["Hồng ngoại", "Tia X"], c: 0 },
    { id: 165, q: "Mặt Trăng hoàn thành chu kỳ quay quanh Trái Đất mất khoảng bao nhiêu ngày?", a: ["27-28 ngày", "365 ngày"], c: 0 },
    { id: 166, q: "Bộ đồ du hành giúp bảo vệ phi hành gia khỏi bức xạ và áp suất bằng 0 đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 167, q: "Ngôi sao nào nằm ở vị trí gần Trái Đất nhất nếu không tính Mặt Trời?", a: ["Proxima Centauri", "Sirius"], c: 0 },
    { id: 168, q: "Vùng không gian xung quanh một hành tinh chịu lực từ trường của nó gọi là gì?", a: ["Từ quyển", "Khí quyển"], c: 0 },
    { id: 169, q: "Gió mặt trời là luồng các hạt mang điện phóng mạnh ra từ Mặt Trời đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 170, q: "Cực quang là hiện tượng ánh sáng nhảy múa xuất hiện ở hai vùng cực hành tinh đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 171, q: "Loài cây lớn nhất thế giới tính theo tổng thể tích thân gỗ là cây gì?", a: ["Sequoia khổng lồ", "Cây thông"], c: 0 },
    { id: 172, q: "Sa mạc lớn nhất trên Trái Đất tính cả các vùng lạnh là sa mạc nào?", a: ["Nam Cực", "Sahara"], c: 0 },
    { id: 173, q: "Châu lục nào giữ kỷ lục lạnh nhất và khô hạn nhất trên Trái Đất?", a: ["Nam Cực", "Châu Âu"], c: 0 },
    { id: 174, q: "Đỉnh núi Everest là đỉnh núi cao nhất hành tinh nếu tính từ mực nước biển đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 175, q: "Đại dương nào có diện tích lớn nhất và độ sâu sâu nhất trên Trái Đất?", a: ["Thái Bình Dương", "Đại Tây Dương"], c: 0 },
    { id: 176, q: "Rừng rậm Amazon được mệnh danh là lá phổi xanh của Trái Đất đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 177, q: "Hiện tượng nguyệt thực toàn phần chỉ có thể xảy ra vào đêm trăng tròn đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 178, q: "Sông Nile là con sông có chiều dài dài nhất trên thế giới đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 179, q: "Điểm sâu nhất của đại dương nằm tại rãnh địa chất nào?", a: ["Rãnh Mariana", "Rãnh Java"], c: 0 },
    { id: 180, q: "Thủy tinh công nghiệp được sản xuất chủ yếu từ nguyên liệu nào?", a: ["Cát silic", "Đất sét"], c: 0 },
    { id: 181, q: "Cơ thể một người trưởng thành bình thường chứa khoảng bao nhiêu nước?", a: ["60-70%", "10-20%"], c: 0 },
    { id: 182, q: "Nhóm máu nào được mệnh danh là nhóm máu chuyên cho trong y học?", a: ["Nhóm máu O", "Nhóm máu AB"], c: 0 },
    { id: 183, q: "DNA là chuỗi phân tử chứa toàn bộ thông tin di truyền của sinh vật đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 184, q: "Trái tim của con người bình thường được cấu tạo chia làm mấy ngăn?", a: ["4 ngăn", "2 ngăn"], c: 0 },
    { id: 185, q: "Thành phần xương có kích thước lớn nhất và nặng nhất cơ thể người là gì?", a: ["Xương đùi", "Xương cánh tay"], c: 0 },
    { id: 186, q: "Cơ quan nào lớn nhất trên cơ thể người nếu tính theo diện tích bề mặt?", a: ["Da", "Gan"], c: 0 },
    { id: 187, q: "Tế bào bạch cầu đảm nhận chức năng chính là tiêu diệt vi khuẩn xâm nhập đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 188, q: "Phổi phải của người bình thường có 3 thùy còn phổi trái chỉ có 2 thùy đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 189, q: "Vitamin C đóng vai trò giúp tăng cường hệ miễn dịch và chống oxy hóa đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 190, q: "Thuốc kháng sinh chỉ có tác dụng diệt vi khuẩn, không diệt được virus đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 191, q: "Chim yến xây dựng tổ của chúng bằng chính nước bọt tiết ra đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 192, q: "Loài thú mỏ vịt nuôi con non bằng sữa tiết ra trực tiếp từ các tuyến da đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 193, q: "Thỏ có tập tính ăn lại phân của chính mình để hấp thụ triệt để dinh dưỡng đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 194, q: "Ve sầu đực phát ra tiếng kêu to chủ yếu nhằm mục đích thu hút bạn tình đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 195, q: "Con hươu cao cổ sở hữu số lượng đốt sống cổ bằng đúng với con người đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 196, q: "Loài kiến trong suốt vòng đời của mình hoàn toàn không bao giờ ngủ đúng không?", a: ["Đúng", "Sai"], c: 1 },
    { id: 197, q: "Cá ngựa đực là đối tượng trực tiếp mang thai và chuyển dạ đẻ con đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 198, q: "Sừng tê giác cấu tạo chủ yếu từ keratin giống thành phần của tóc và móng đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 199, q: "Gấu trúc có chế độ ăn uống cấu tạo tới 99% nguồn từ cây tre, trúc đúng không?", a: ["Đúng", "Sai"], c: 0 },
    { id: 200, q: "Khí methane (CH4) có thể sinh ra từ hệ tiêu hóa của động vật ăn cỏ đúng không?", a: ["Đúng", "Sai"], c: 0 }
];